apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-k8s-demo-deployment
  labels:
    app: docker-k8s-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-k8s-demo
  template:
    metadata:
      labels:
        app: docker-k8s-demo
    spec:
      containers:
        - name: docker-k8s-demo
          image: winnie2949/demo:1.0
          env:
            - name: "PORT"
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: docker-k8s-demo-service
spec:
  type: LoadBalancer
  selector:
    app: docker-k8s-demo
  ports:
    - protocol: TCP
      port: 60000
      targetPort: 8080