# Spring Boot Setting --------------------------------------------------------------------------------------------------
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-circular-references: true
# Database Setting -----------------------------------------------------------------------------------
  datasource:
    url: jdbc:sqlserver://34.135.251.234;databaseName=demo;encrypt=true;trustServerCertificate=true;
    username: ENC(9Jqd70PytxngeR2/pn+N5Hv/+hEJ8x6l6t3ZE70xel6WF8UyVeDmk0NlLsK4ylxt)
    password: ENC(MWa/oc684tCMQzOwzM0rhqkvaS8hbxYivQ788Ue1/JjUQMWwkqIYqyFE/1K4VhxNfjP8mHWsBTiOb/TDK0vtXQ==)
# Kafka Setting --------------------------------------------------------------------------------------------------------
app:
  topic:
    transaction: transaction

# logging Setting ------------------------------------------------------------------------------------------------------
logging:
  level:
    root: WARN
    org.springframework.web: INFO
    com.winnie: TRACE
  file:
    name: ./log/log.log
  logback:
    rollingpolicy:
      max-history: 90
      max-file-size: 10MB


