# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  gcp-gke: circleci/gcp-gke@1.4.0
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build-and-test:
    working_directory: ~/demo
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: circleci/openjdk:8-jdk
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - setup_remote_docker
      - run: mvn clean package
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/demo-0.0.1-SNAPSHOT.jar
      - run:
          name: build and push Docker image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t winnie2949/demo:$TAG .
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD 
            docker push winnie2949/demo:$TAG
  deploy:
    steps:
      - checkout
      - gcp-gke/install
      - gcp-gke/init
      - gcp-gke/rollout-image:
          deployment: autopilot-cluster-1
          container: dominic-backend
          image: winnie2949/demo:0.1.$CIRCLE_BUILD_NUM
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
